openapi: 3.0.0
info:
  title: "My Web Service API"
  version: "1.0.0"
  description: "API per la gestione di segnaposti, cacce al tesoro e quiz."
servers:
  - url: "http://localhost:3000/api/v1"
paths:
  /api/maps-config.js:
    get:
      summary: Restituisce la chiave API di Google Maps in formato JavaScript
      description: >
        Questo endpoint fornisce la chiave API di Google Maps sotto forma di file JavaScript.  
        La chiave viene caricata come variabile globale `window.GOOGLE_MAPS_API_KEY`.  
        **Nota:** La chiave API è esposta in chiaro ma è stata limitata a richieste da domini specifici.
      responses:
        "200":
          description: File JavaScript contenente la chiave API
          content:
            application/javascript:
              schema:
                type: string
                example: 'window.GOOGLE_MAPS_API_KEY = "YOUR_API_KEY";'
