openapi: 3.0.0
info:
  title: "My Web Service API"
  version: "1.0.0"
  description: "API per la gestione di segnaposti, cacce al tesoro e quiz."
servers:
  - url: "http://localhost:3000"


tags:
  - name: "Segnaposti"
    description: "Gestione dei segnaposti"
  - name: "Quiz"
    description: "Gestione dei quiz"
  - name: "Caccia al Tesoro"
    description: "Gestione delle cacce al tesoro"
  - name: "Google Maps"
    description: "Gestione della chiave API di Google Maps" 






paths:
  /api/maps-config.js:
    get:
      tags:
        - "Google Maps"
      summary: Restituisce la chiave API di Google Maps in formato JavaScript
      description: >
        Questo endpoint fornisce la chiave API di Google Maps sotto forma di file JavaScript.  
        La chiave viene caricata come variabile globale `window.GOOGLE_MAPS_API_KEY`.  
        **Nota:** La chiave API è esposta in chiaro ma è stata limitata a richieste da domini specifici.
      responses:
        "200":
          description: File JavaScript contenente la chiave API
          content:
            application/javascript:
              schema:
                type: string
                example: 'window.GOOGLE_MAPS_API_KEY = "YOUR_API_KEY";'



  /api/v1/segnaposti:
    get:
      tags:
        - "Segnaposti"
      summary: Ottieni tutti i segnaposti
      responses:
        '200':
          description: Lista di segnaposti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Segnaposto'
        '500':
          description: Errore interno del server
    post:
      tags:
        - "Segnaposti"
      summary: Crea un nuovo segnaposto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Segnaposto'
      responses:
        '201':
          description: Segnaposto creato con successo
        '400':
          description: Dati non validi



  /api/v1/segnaposti/{id}:
    get:
      tags:
        - "Segnaposti"
      summary: Ottieni un segnaposto specifico per ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del segnaposto da recuperare
          schema:
            type: string
      responses:
        '200':
          description: Segnaposto trovato con successo e restituito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Segnaposto'
        '404':
          description: Segnaposto non trovato
        '500':
          description: Errore del server
    put:
      tags:
        - "Segnaposti"
      summary: Aggiorna un segnaposto
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Segnaposto'
      responses:
        '200':
           description: Segnaposto aggiornato con successo
        '400':
          description: Dati non validi
        '404':
          description: Segnaposto non trovato
    delete:
      tags:
        - "Segnaposti"
      summary: Elimina segnaposto
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description : Segnaposto eliminato con successo
        '404':
          description: segnaposto non trovato
        '500':
          description: errore del server'
    

  /api/v1/segnaposti/{id}/quiz/{quizId}:
    post: 
      tags:
        - Segnaposti
      summary: Aggiungi un quiz a un segnaposto
      description: Associa un quiz esistente a un segnaposto esistente.
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del segnaposto
        - in: path
          name: quizId
          required: true
          schema:
            type: string
          description: ID del quiz da aggiungere
      responses:
        '200':
          description: Quiz aggiunto con successo al segnaposto
        '404':
          description: Segnaposto o quiz non trovato

    delete:
      tags:
        - Segnaposti
      summary: Rimuovi un quiz da un segnaposto
      description: Rimuove l'associazione tra un quiz e un segnaposto esistente.
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del segnaposto
        - in: path
          name: quizId
          required: true
          schema:
            type: string
          description: ID del quiz da rimuovere
      responses:
        '200':
          description: Quiz rimosso con successo dal segnaposto
        '404':
          description: Segnaposto o quiz non trovato






  /api/v1/quiz:
    get:
      tags:
        - "Quiz"
      summary: Ottieni tutti i quiz
      responses:
        '200':
          description: Lista di quiz
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quiz'
        '500':
          description: Errore interno del server

    post:
      tags:
        - "Quiz"
      summary: Crea un nuovo quiz
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        '201':
          description: Quiz creato con successo
        '400':
          description: Dati non validi
  
  /api/v1/quiz/{id}:
    get:
      tags:
        - "Quiz"
      summary: Ottieni un quiz specifico per ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del quiz da recuperare
          schema:
            type: string
      responses:
        '200':
          description: Quiz trovato con successo 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
        '404':
          description: Quiz non trovato
        '500':
          description: Errore del server
    
    put:
      tags:
        - "Quiz"  
      summary: Aggiorna un quiz specifico
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        '200':
           description: Quiz aggiornato con successo
        '400':
          description: Dati non validi
        '404':
          description: Quiz non trovato
    
    delete:
      tags:
        - "Quiz"
      summary: Elimina quiz specifico
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description : Quiz eliminato con successo
        '404':
          description: quiz non trovato
        '500':
          description: errore del server

  /api/v1/cacciaAlTesoro:
    get:
      tags:
        - "Caccia al Tesoro"
      summary: Ottieni la lista di tutte le cacce al tesoro
      responses:
        '200':
          description: Lista di cacce al tesoro
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CacciaAlTesoro'
    post:
      tags:
        - "Caccia al Tesoro"  
      summary: Crea una nuova caccia al tesoro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CacciaAlTesoro'
      responses:
        '201':
          description: Caccia al tesoro creata con successo
        '400':
          description: Dati non validi

    
      
  /api/v1/cacciaAlTesoro/{id}:
    get:
      tags:
        - "Caccia al Tesoro"
      summary: Ottieni una caccia al tesoro specifica per ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID della caccia al tesoro da recuperare
          schema:
            type: string
      responses:
        '200':
          description: Caccia al tesoro trovata con successo 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacciaAlTesoro'
        '404':
          description: Caccia al tesoro non trovata
        '500':
          description: Errore del server
          
    delete:
      tags:
        - "Caccia al Tesoro"
      summary: Elimina una caccia al tesoro
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description : Caccia al tesoro eliminata con successo
        '404':
          description: Caccia al tesoro non trovata
        '500':
          description: Errore del server       
    
  /api/v1/cacciaAlTesoro/{id}/segnaposti/{segnapostoId}:
    post:
      tags:
        - Caccia al Tesoro
      summary: Aggiungi un segnaposto a una caccia al tesoro
      description: Associa un segnaposto esistente a una caccia al tesoro esistente.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID della caccia al tesoro
        - in: path
          name: segnapostoId
          required: true
          schema:
            type: string
          description: ID del segnaposto da aggiungere
      responses:
        '200':
          description: Segnaposto aggiunto con successo
        '404':
          description: Caccia al tesoro o segnaposto non trovati

    delete:
      tags:
        - Caccia al Tesoro
      summary: Rimuovi un segnaposto da una caccia al tesoro
      description: Rimuove un'associazione tra una caccia al tesoro e un segnaposto.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID della caccia al tesoro
        - in: path
          name: segnapostoId
          required: true
          schema:
            type: string
          description: ID del segnaposto da rimuovere
      responses:
        '200':
          description: Segnaposto rimosso con successo dalla caccia al tesoro
        '404':
          description: Caccia al tesoro o segnaposto non trovati
      



components:
  schemas:

    Risposta:
      type: object
      required:
        - testo
      properties:
        testo:
          type: string
          example: "Nella prima metà del 1200"
        corretta:
          type: boolean
          default: false
          example: true
      

    Quiz:
      type: object
      required:
        - domanda
        - risposte
      properties:
        domanda:
          type: string
          example: "Quando è stato costruito il castello del Buonconsiglio?"
        risposte:
          type: array
          items:
            $ref: '#/components/schemas/Risposta'
        punti:
          type: integer
          minimum: 0
          example: 5
    


    Segnaposto:
      type: object
      properties:
        titolo:
          type: string
          example: "Duomo di Trento"
        descrizione:
          type: string
          example: "La principale cattedrale di Trento."
        indirizzo:
          type: string
          example: "Piazza Duomo, Trento"
        quiz:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Quiz'
        punti:
          type: integer
          example: 10
        indizio:
          type: string
          nullable: true
          example: "Dirigiti alla chiesa più importante di Trento."
        coordinate:
          type: object
          properties:
            lat:
              type: number
              format: float
              example: 46.066667
            lng:
              type: number
              format: float
              example: 11.116667

    CacciaAlTesoro:
      type: object
      properties: 
        titolo:
          type: string
          example: "Caccia lungo l'Adige"
        descrizione:
          type: string
          example: "La caccia al tesoro si sviluppa principalmente lungo il fiume Adige e andra a a toccare i principali punti di interesse "
        segnaposti:
          type: array
          items:
            $ref: '#/components/schemas/Segnaposto'
